### ISSUE TITLE
h5writeDataset.data.frame function not found

### ISSUE THREAD

**Issue by koustav-pal** [Huber-group-EMBL/rhdf5#103]
Hi, 

I have a package which depends on the h5writeDataset.data.frame function within rhdf5. However, it can no longer be found. Has this function been deprecated?

**Comment by grimbough** [comment]
Hi, I think this is the same issue reported in https://github.com/grimbough/rhdf5/issues/98

You should find that you can just use `h5writeDataset()` directly on your data.frame, and don't need to explicitly use `h5writeDataset.data.frame()` directly.  However, if that's not the case please let me know and I'll take a closer look.
