### ISSUE TITLE
A problem when installing sleuth package related to "rhdf5"

### ISSUE THREAD

**Issue by DreamAtDawn** [Huber-group-EMBL/rhdf5#105]
Forgive me about my naive question. But the thing is when I was installing the 'sleuth' package, an error turned up and said like:

* installing *source* package ‘sleuth’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error: object ‘h5write.default’ is not exported by 'namespace:rhdf5'
Execution halted
ERROR: lazy loading failed for package ‘sleuth’
* removing ‘/Library/Frameworks/R.framework/Versions/4.1/Resources/library/sleuth’

I've read a similar cases on the Internet, and Im wandering if it is because the rhdf5 package has been updated and 'h5write.default' has been renamed so that the installation programe cannnot find the thing with its previous name? What should I do... : ( 
Begging for help . Thx : )

**Comment by grimbough** [comment]
This is related to #98 and it looks like it's also been reported on the Sleuth repository in https://github.com/pachterlab/sleuth/issues/259  I think it's up to the Sleuth maintainers to patch their package to cope with this change.
