### ISSUE TITLE
`h5write` truncates UTF-8 strings

### ISSUE THREAD

**Issue by LTLA** [Huber-group-EMBL/rhdf5#111]
```r
library(rhdf5)
h5createFile("ex_hdf5file.h5")
h5write("α ≤ 0.1", "ex_hdf5file.h5", "WHEE")
h5read("ex_hdf5file.h5", "WHEE")
## [1] "α ≤ "
```

This is because `nchar` should have been called with `type="byte"` to get the actual byte length, not character length.

While we're at it, if `encoding = NULL`, you can choose `"UTF-8"` based on the value of `Encoding(obj)`. This would be more faithful to the in-memory representation of the string in R.

**Comment by grimbough** [comment]
This is hopefully fixed in version 2.41.1

```r
packageVersion("rhdf5")
#> [1] ‘2.41.1’
library(rhdf5)
h5createFile("ex_hdf5file.h5")
h5write("α ≤ 0.1", "ex_hdf5file.h5", "WHEE")
output <- h5read("ex_hdf5file.h5", "WHEE")
output
#> [1] "α ≤ 0.1"
```

It also sets the encoding to UTF-8 in R, if that's what the HDF5 dataset uses.

```r
Encoding(output)
#> [1] "UTF-8"
```
