### ISSUE TITLE
HST_ typos?

### ISSUE THREAD

**Issue by mtmorgan** [Huber-group-EMBL/rhdf5#14]
There are 8 labels "HST_" in src/printdatatype.c; should these be "H5T_" ?

**Comment by grimbough** [comment]
Thanks for pointing this out.  I think the only place its is visible is the output from `h5ls()` and `h5dump()` with the argument `all = TRUE` e.g.
```
> h5write(LETTERS, file = "/tmp/test.h5", name = "LETTERS")
> h5ls('/tmp/test.h5', all = TRUE)$dtype
[1] "HST_STRING"
```

Should be fixed in [c647f7a](https://github.com/grimbough/rhdf5/commit/c647f7a27fb9c7b2993c4aa9c142fbbe7e5d8fd9) e.g.

```
h5ls('/tmp/test.h5', all = TRUE)$dtype
[1] "H5T_STRING"
```
