### ISSUE TITLE
dimension missing in h5ls()

### ISSUE THREAD

**Issue by thomasmooon** [Huber-group-EMBL/rhdf5#16]
Thanks a lot for providing this package!

Unfortunately the dimension of a particular dataset does not appear. Here's an example:
```

library(rhdf5)
h5createFile("iris.h5")
h5write(iris,"iris.h5","iris_dataframe")
h5ls("iris.h5")

```
Here's the output of that example. As one can see in the last column "dim": It's empty.
![image](https://user-images.githubusercontent.com/29228225/40058926-f979d658-5852-11e8-8a39-6c40103129d4.png)

This is independent of the data type (vector, matrix, dataframe), the rank and the dimension.

> > sessionInfo()
> R version 3.3.2 (2016-10-31)
> Platform: x86_64-redhat-linux-gnu (64-bit)
> Running under: Red Hat Enterprise Linux Server release 6.8 (Santiago)
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] rhdf5_2.18.0      medicalrisk_1.2   data.table_1.11.2 dplyr_0.5.0      
> 
> loaded via a namespace (and not attached):
>  [1] hash_2.2.6      Rcpp_0.12.7     knitr_1.20      magrittr_1.5    zlibbioc_1.20.0 R6_2.2.2        stringr_1.3.0   highr_0.6       plyr_1.8.4      tools_3.3.2    
> [11] DBI_1.0.0       htmltools_0.3.6 yaml_2.1.18     lazyeval_0.2.1  assertthat_0.1  rprojroot_1.3-2 digest_0.6.12   Rserve_1.7-3    tibble_1.2      reshape2_1.4.1 
> [21] tidyr_0.6.0     base64enc_0.1-3 evaluate_0.10.1 rmarkdown_1.9   stringi_1.1.7   backports_1.1.2 jsonlite_1.5

**Comment by grimbough** [comment]
There was a similar report to this a while back on the Bioconductor support site (https://support.bioconductor.org/p/101038/) where one dimension (of two) wasn't being reported in `h5ls()`.  In that case upgrading to the latest version of R and **rhdf5** removed the issue.  

I notice you're using a pretty old version of both, does updating this fix it for you too?

**Comment by thomasmooon** [comment]
Thanks for the quick support. I've raised an update request at my company, since I'm not allowed and able to perform an R-Update. Hence I can't give you a clear feedback for your suggestion right now. But I will, as soon as I can provide news.
