### ISSUE TITLE
update hdf5 library version

### ISSUE THREAD

**Issue by mtmorgan** [Huber-group-EMBL/rhdf5#18]
in reference to https://support.bioconductor.org/p/109845/#109881 it seems like libhdf5 1.10 can (as expected) [read files created by older libraries][1], but not vice versa, so updating to 1.10 might not have major down-sides (other than x hours of effort!).

[1]: https://support.hdfgroup.org/HDF5/docNewFeatures/

**Comment by grimbough** [comment]
I guess this really wants to be an issue at https://github.com/grimbough/Rhdf5lib ?  

When I first started creating Rhdf5lib I know I started with HDF5 version 1.10, but encountered problems getting it to work on Windows, so I reverted to 1.8 at that point.  I know a hell of a lot more about building HDF5 now though, so maybe I can avoid those problems if it makes everything a bit more future proof.

**Comment by grimbough** [comment]
This is a lot more tricky than expected, as HDF5 moved from 32bit to 64bit integers for the internal handles.  Since we pass these between C and R in almost every function it breaks a lot of things.  Currently working in the `tenPointTwo` branch to try and solve this.
