### ISSUE TITLE
rhdf5 install on OSX 10.11.6 (system_lib branch) to link to hdf-10.2

### ISSUE THREAD

**Issue by nwieder** [Huber-group-EMBL/rhdf5#20]
Hi,

I've been trying to rebuild rhdf5 to link it to the hdf5-10.2 library which I installed via macports. 
Problem here is that macports does not generate .so files but only .dylib and .a. I was looking into building hdf5 from source, but somehow there is no info on that on the hdf5 homepage and everything they provide is for linux / windows. 

I think there are multiple ways to fix that issue (including compiling hdf5 form source), but maybe it is the easiest for you to add compiler flags for static libraries?

Thanks,

Nico

**Comment by grimbough** [comment]
Hi Nico,

I don't really want to support the `system_lib` branch too much as it opens a rabbit hole of support issues when any HDF5 version can be used. 

However, in a rather roundabout answer to your request, but I've updated **rhdf5** and **Rhdf5lib** to use HDF5 1.10.2 directly.  Hopefully that will be sufficient for your needs.  They'll make it into the BioC devel branch in the next few days, but you can inntall directly via:

```
BiocManager::install('grimbough/Rhdf5lib')
BiocManager::install('grimbough/rhdf5')
```

It's been a pretty major overhaul, so let me know if anything funky happens.

Mike

**Comment by nwieder** [comment]
Hi Mike,

Thanks for the reply. I will try out the updated version of rhdf5 as soon as I find some time!
Closing this issue.

nico
