### ISSUE TITLE
Make error message explicit for large data chunksize

### ISSUE THREAD

**Issue by bharris12** [Huber-group-EMBL/rhdf5#32]
When you don't set a chunksize for larger data it will throw this error:

`Error in H5Dcreate(loc$H5Identifier, dataset, tid, sid, dcpl = dcpl): HDF5. Dataset. Unable to initialize object.
Traceback:

1. h5createDataset(fn, "all_exprs", dim(all_exprs), level = 9)
2. H5Dcreate(loc$H5Identifier, dataset, tid, sid, dcpl = dcpl)`

Make the error message for this explicit so that the user knows that they need to set a chunksize that is smaller

**Comment by grimbough** [comment]
I presume you're getting to here via `h5write()`?  How large is 'larger'?  I've not seen it throw this error before.

It'd be great if you could provide a more complete example, so I can test a fix.  It's certainly possible to create datasets where the chunk size is the same as the dataset, and **rhdf5** currently gives a warning if they're larger than 1,000,000 entries.

**Comment by bharris12** [comment]
![image](https://user-images.githubusercontent.com/12770143/51571268-b0ec7380-1e6f-11e9-96b0-8320ad2ad0a4.png)

I am aware that it gives the warning about the chunksize. But that warning does not explicitly say that you will get an error if your dataset is big enough. It would be a lot better if h5write() changed the chunksize automatically if the data is large or gave an clear error that you need to specify a smaller chunksize. My matrix is 62787 x  9375 double.

**Comment by grimbough** [comment]
Turns out there's a 4GB limit on any chunk, which your dataset exceeds if represented by a single chunk.

As of **rhdf5** 2.27.6 `h5createDataset()` will check the size of specified chunks & reduce them if necessary.  It also produces a message letting you know this has happened, and suggesting using the `chunks` argument if the automatic values are not appropriate e.g.

```r
library(rhdf5)
h5f <- tempfile(fileext = ".h5")
h5createFile(h5f)
h5createDataset(file = h5f, dataset = 'data',
                dims = c(62787, 9375), level = 2,
                storage.mode = "double")
```
```
Current chunk settings will exceed HDF5's 4GB limit.
Automatically adjusting them to: 23170 x 9375
You may wish to set these to more appropriate values using the 'chunk' argument.
```
