### ISSUE TITLE
expose H5L_MOVE or H5L_COPY?

### ISSUE THREAD

**Issue by FelixErnst** [Huber-group-EMBL/rhdf5#41]
Would it be possible to expose the H5L_MOVE or H5L_COPY function in `rhdf5`?

I would like to be able to use the function to restructure groups and datasets after they have been written to file without going through a read, delete, write cycle. My experience using HDF5 files is quite limited, so if exposing these function is generally not advised, because I lack some background information, please let me know.

**Comment by FelixErnst** [comment]
any chance this might be something for the future?

**Comment by grimbough** [comment]
These should now be available in version 2.29.4.  It's only on github for the moment, but should make it through to BioC devel in a day or so.  Let me now if you encounter any issues.
