### ISSUE TITLE
Linking to rhdf5

### ISSUE THREAD

**Issue by dipterix** [Huber-group-EMBL/rhdf5#59]
Hi, 
Is it possible to make a static file headers to provide API for other R packages with cpp or c code directly linking to your c headers?

[#Linking-to-other-packages](https://cran.rstudio.com/doc/manuals/r-devel/R-exts.html#Linking-to-other-packages)

Basically it requires static header files from your package in `inst/include/` path so that I can extend your package without copying and edit yours. 

Here's an [example](https://github.com/fstpackage/fstcore/tree/master/inst/include) from some another package.

**Comment by grimbough** [comment]
What feature of rhdf5 do you want access to?  I'm wondering if https://github.com/grimbough/Rhdf5lib would be more useful to you.  That package wraps the standard HDF5 library and allows you to link against it using your own C code from a package.
