### ISSUE TITLE
large parts of the HDF5 API missing

### ISSUE THREAD

**Issue by ilia-kats** [Huber-group-EMBL/rhdf5#94]
I noticed that a lot of HDF5 functionality is not exposed through rhdf5. All of the C code seems to have been written a long time ago, but it is commented out, and no R wrappers exist. Please consider making it available to R. In particular, I need to be able to set the userblock size upon file creation (`H5Pset_userblock`).

**Comment by grimbough** [comment]
Sure, I tend to add parts of the API when I get a request like this or when I run into a use case myself that needs a new addition. 

I'll take a look at adding your missing function in the next few weeks, but also welcome pull requests.
